/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MainPage: typeof import('./components/pages/MainPage.vue')['default']
    MyProfile: typeof import('./components/pages/MyProfile.vue')['default']
    PageHeader: typeof import('./components/PageHeader.vue')['default']
    ProductCardComponent: typeof import('./components/productCardComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
